name = "ta-garden-landing"
compatibility_date = "2024-01-01"
main = "src/worker.js"

[assets]
directory = "./public"
html_handling = "none"

[[kv_namespaces]]
binding = "BOOKINGS"
id = "8d5879ddbfb64e4ca94643fa844645fd"

[triggers]
crons = ["0 1 * * *"]

